export const TIMELINE_CONSTANTS = {
  DEFAULT_TRACK_HEIGHT: 48,
  MIN_ELEMENT_WIDTH: 20,
  PIXELS_PER_SECOND: 100,
  SNAP_THRESHOLD: 8,
  ZOOM_MIN: 0.1,
  ZOOM_MAX: 10,
  ZOOM_DEFAULT: 1,
};

export const DEFAULT_ELEMENT_DURATION = 5;
